Add missing parent IDs, other fixes
awslabs/aws-progress-monitor pull request #3
Opened 2017-06-08 15:28 UTC by jfwood

Add setting of the parent ID on trackers, fix DynamoDB logic, fix
integer conversion math, fix some logging lines.

2017-06-09 15:08 UTC, jfwood commented
test comment

2017-06-09 15:13 UTC, troylar requested changes

2017-06-09 15:13 UTC, troylar commented on progressmonitor/__init__.py
> +            t.with_estimated_seconds(int(j['EstimatedSeconds']), True)
Just curious, why are we converting to int?

2017-06-09 15:13 UTC, troylar commented on progressmonitor/__init__.py
> +    def prepare_for_dynamodb(cls, data_store):
Can we just cast individual properties in the to_update_item method instead of using this method?

Example: 
Change
```
if self.estimated_seconds:
             ue = ue + ', EstimatedSeconds=:est_sec'
             eav[':est_sec'] = self.estimated_seconds
```
to
```
if self.estimated_seconds:
             ue = ue + ', EstimatedSeconds=:est_sec'
             eav[':est_sec'] = str(self.estimated_seconds)
```
I feel like this method is pretty brute force. Because there's only a few fields and there's only a couple float/datetime fields, it seems to fit in the to_update_item. @jfwood

2017-06-09 15:13 UTC, troylar commented on progressmonitor/__init__.py
> +    def prepare_for_dynamodb(cls, data_store):
@jfwood

2017-06-09 15:13 UTC, jfwood commented on progressmonitor/__init__.py
> +    @classmethod
A test comment for @troylar.....this could be a @staticmethod.

2017-06-09 15:14 UTC, jfwood commented on progressmonitor/__init__.py
> +            t.with_estimated_seconds(int(j['EstimatedSeconds']), True)
This is coming back out of dynamo as a Decimal type. We could convert to float here instead, or just deal with Decimals. They don't play nice with arithmetic involving floats though

2017-06-09 15:16 UTC, jfwood commented on progressmonitor/__init__.py
> +    def prepare_for_dynamodb(cls, data_store):
yep, will do shortly.

2017-06-14 00:31 UTC, jfwood commented
@troylar, just added a fix for a dynamoDB issue that @xzased found and suggested a fix for. I've also addressed your requested change as well I believe.

2017-06-21 09:52 UTC, merged